### ISSUE TITLE
reloading on /[roomid] causes user to exit the room and redirects to home page

### ISSUE THREAD

**Issue by sohamdata** [nainglinnkhant/scribble#10]
to reproduce:
- on home page enter username and create room
- refresh

**Comment by nainglinnkhant** [comment]
Thanks for raising the issue. Actually, this behavior is expected as Scribble doesn't use any database. Plus, actions such as undo and draw will take a lot of time to execute if server states like undo points are stored in the database which is an immense drawback that we don't want.

**Comment by sohamdata** [comment]
ah right, great project btw, I'm building something similar for a different purpose.

**Comment by nainglinnkhant** [comment]
Good luck crafting yours!
