### ISSUE TITLE
I am not able to create room

### ISSUE THREAD

**Issue by shaikahmadnawaz** [nainglinnkhant/scribble#11]
![image](https://github.com/nainglinnkhant/scribble/assets/96189881/6b12abbc-5cab-4a66-abf7-7e54e36293c4)

**Comment by nainglinnkhant** [comment]
My railway trial has ended. I'll try to find a new server hosting service with the free tier.

**Comment by nainglinnkhant** [comment]
Thanks for raising the issue. My Railway trial has ended. I'll try to find a new server hosting service with the free tier.

**Comment by nainglinnkhant** [comment]
I have just upgraded to the hobby plan on Railway. Scribble is running again now.

**Comment by shaikahmadnawaz** [comment]
> I have just upgraded to the hobby plan on Railway. Scribble is running again now.

Great then, I am closing this issue now.
