### ISSUE TITLE
reloading /[roomId] redirects to home page

### ISSUE THREAD

**Issue by HLrahul** [nainglinnkhant/scribble#18]
when a user intentionally or accidentally reloads the /[roomId] page he will be redirected to the home page.

**Comment by nainglinnkhant** [comment]
Thanks for raising the issue, but this is the intended behavior. Please check this: https://github.com/nainglinnkhant/scribble/issues/10#issuecomment-1655846183.

**Comment by HLrahul** [comment]
I knew that it was intended, when I saw you were returning the client to the home page after checking the store for user's state! 

I thought this might be a good add to the app. Let me know if it adds some value.

**Comment by nainglinnkhant** [comment]
I saw it, thanks. I'm currently busy with my work. I'll review your PR later.
