### ISSUE TITLE
Debugger with module-aliases problem

### ISSUE THREAD

**Issue by ckstn0777** [nainglinnkhant/scribble#33]
Hey, I am trying to use the VsCode debugger and it seems to have a problem with the module-alias package.

![image](https://github.com/nainglinnkhant/scribble/assets/44571683/cd66445e-c53a-4b0d-a2cf-9bc9d8733b42)

How can it be resolved?

**Comment by nainglinnkhant** [comment]
Hey, sorry for not replying earlier. I had to take a break from open-source stuff since I was busy with my studies and full-time job. Is the issue solved now? If not, would love to help.
